name: Run main.py

on:
  schedule:
    - cron: '0 17 * * *'  # 台灣時間凌晨1點（UTC+8 → UTC-8）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        env:
          GCP_KEY_BASE64: ${{ secrets.GCP_KEY_BASE64 }}
        run: python main.py
